### ISSUE TITLE
Desc structure

### ISSUE THREAD

**Issue by charlotteassemat** [CamilleMaurice/VATS_project_assemat_maurice#1]
on a vraiment besoin de stocker la first frame dans la struct desc en fait??

**Comment by CamilleMaurice** [comment]
nop, ca ne sert a rien c'est juste que quand j'ai commence a decrire la
structure jai mis des trucs dedans et j'ai oublie de l'enlever par la suite

2015-04-04 17:10 GMT+02:00 charlotteassemat <notifications@github.com>:

**Comment by CamilleMaurice** [comment]
Je comprends pas trop l'interet d'avoir separer bg model et foreground
segmentation... du coup on parcourt 2 fois l'image non?

**Comment by charlotteassemat** [comment]
oui dans le descriptif javais limpression que cets ce quil fallait faire (?)
